name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.0.x
          8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Debug
      run: dotnet build --no-restore --configuration Debug
    - name: Test
      run: dotnet test --no-build --configuration Debug --verbosity normal
    - name: Build Release
      run: dotnet build --no-restore --configuration Release
    - name: Read Version
      id: read_version
      run: echo "VERSION=$(jq -r .version project.json)" >> $GITHUB_OUTPUT
    - name: Pack
      run: dotnet pack --no-build --configuration Release -o ./nupkg /p:PackageVersion=${{ steps.read_version.outputs.VERSION }}
    - name: Publish to NuGet
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push ./nupkg/*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
