name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Read Version
      id: read_version
      run: echo "VERSION=$(jq -r .version project.json)" >> $GITHUB_OUTPUT
    - name: Pack
      run: dotnet pack --no-build -o ./nupkg /p:PackageVersion=${{ steps.read_version.outputs.VERSION }}
    - name: Publish to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push ./nupkg/*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json      
    - name: Publish to NuGet
          if: github.event_name == 'push' && github.ref == 'refs/heads/main'
          env:
            NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          run: dotnet nuget push ./nupkg/*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json